unqualified-search-registries = ["docker.io"]

[[registry]]
prefix = "docker.io"
location = "mirror.ccs.tencentyun.com"

[[registry]]
prefix = "quay.io"
location = "quay.mirrors.ustc.edu.cn"

[[registry]]
prefix = "gcr.io"
location = "gcr.mirrors.ustc.edu.cn"

[[registry]]
prefix = "k8s.gcr.io"
location = "k8s.mirrors.ustc.edu.cn"

[[registry]]
prefix = "registry.k8s.io"
location = "registry.k8s.io.mirrors.ustc.edu.cn"
